version: "3.9"

services:

  mysql:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  #postgres:
    #image: postgres:14.2
    #restart: always
    #environment:
      #POSTGRES_USER: root
      #POSTGRES_PASSWORD: root
    #ports:
      #- 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080